package main

import (
	"fmt"
	"os"
)

func showHelp() {
	fmt.Println("halkoctl - Halko Control Tool")
	fmt.Println()
	fmt.Println("A command-line tool for interacting with the Halko system.")
	fmt.Println()
	fmt.Println("Usage:")
	fmt.Printf("  %s [global-options] <command> [command-options] [arguments]\n", os.Args[0])
	fmt.Println()
	fmt.Println("Global Options:")
	fmt.Println("  -c, --config string")
	fmt.Println("        Path to the halko.cfg configuration file")
	fmt.Println("  -v, --verbose")
	fmt.Println("        Enable verbose output")
	fmt.Println("  -h, --help")
	fmt.Println("        Show this help message")
	fmt.Println()
	fmt.Println("Available Commands:")
	fmt.Println("  send                  Send program to controlunit")
	fmt.Println("  status                Get service status")
	fmt.Println("  running               Show currently running program")
	fmt.Println("  validate              Validate a program file")
	fmt.Println("  display               Send text to sensor unit display")
	fmt.Println("  temperatures          Get current temperatures from sensor unit")
	fmt.Println("  programs              Manage stored programs")
	fmt.Println("  nginx                 Generate nginx proxy configuration")
	fmt.Println()
	fmt.Println("Command Help:")
	fmt.Printf("  %s <command> --help   Show help for a specific command\n", os.Args[0])
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Printf("  %s send example/example-program-delta.json\n", os.Args[0])
	fmt.Printf("  %s status\n", os.Args[0])
	fmt.Printf("  %s running\n", os.Args[0])
	fmt.Printf("  %s --verbose validate my-program.json\n", os.Args[0])
	fmt.Printf("  %s display \"Hello World\"\n", os.Args[0])
	fmt.Printf("  %s temperatures\n", os.Args[0])
	fmt.Printf("  %s programs list\n", os.Args[0])
	fmt.Printf("  %s programs create my-program.json\n", os.Args[0])
	fmt.Printf("  %s nginx -port 8080 -output /etc/nginx/sites-available/halko\n", os.Args[0])
}
