FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ../bin/storage /app/storage
COPY halko.cfg /app/halko.cfg

RUN chmod +x /app/storage

ENTRYPOINT ["./storage", "-c", "/app/halko.cfg", "-v"]
