FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ../bin/powerunit /app/powerunit
COPY halko.cfg /app/halko.cfg

RUN chmod +x /app/powerunit

ENTRYPOINT ["./powerunit", "-c", "/app/halko.cfg", "-v"]
